### ISSUE TITLE
VN name frame overlaps with room buttons on wider screens

### ISSUE THREAD

**Issue by hubb2001** [mertvn/EMQ#50]
On higher-width screens, the top-left buttons are unclickable due to being hidden behind the visual novel name viewport even while a name is not being displayed

![image](https://github.com/mertvn/EMQ/assets/10701044/cbef764f-09bd-4230-b1e2-d9e31c4e93d5)

Fixable by setting the z-index of the buttons to force them to be above.

**Comment by mertvn** [comment]
The UI isn't supposed to be that far up in the first place, so setting the z-index would just be a band-aid fix. It's quite hard for me to properly fix this as I only have a 1080p monitor, so I'll do what you suggest for now.

**Comment by mertvn** [comment]
Need to find a period of time where no one is playing to push the changes live.
