### ISSUE TITLE
Wishlist VNs are not included in EMQ

### ISSUE THREAD

**Issue by lolfoollor** [mertvn/EMQ#51]
I have tried a couple of times in EMQ looting with my VNDB id to test this out but it doesn't seem to include any wishlist VN unless they did not play/vote on vn to begin with like [u236125](https://vndb.org/u236125). 

![image](https://github.com/mertvn/EMQ/assets/68058606/170222d4-b565-4d46-bac9-64e271cfddc2)

**Comment by mertvn** [comment]
By default, VNs under the Wishlist label aren't included. Does this problem occur even though you've set it to Include in the preferences? 
![image](https://github.com/mertvn/EMQ/assets/78761720/5a19b017-fb73-4a4c-844d-3657515b651a)

**Comment by lolfoollor** [comment]
Oh. Thanks for letting me know of this feature. I had assumed that it was in the room settings. After enabling wishlist, it does appear in the looting now. Thanks!
